Maruno17/pokemon-essentials

Data/Scripts/011_Battle/001_Battler/007_Battler_UseMove.rb

This makes dancer work only if a Pokémon uses a dance move (Such as Swords Dance), not when using whichever move. Tested on my copy of V18 and worked

Patch Dancer Ability

---

Data/Scripts/012_Battle/001_Battler/001_PokeBattle_Battler.rb
Data/Scripts/012_Battle/001_Battler/002_Battler_Initialize.rb
Data/Scripts/012_Battle/001_Battler/003_Battler_ChangeSelf.rb
Data/Scripts/012_Battle/001_Battler/007_Battler_UseMove.rb
Data/Scripts/012_Battle/001_Battler/010_Battler_UseMove_TriggerEffects.rb
Data/Scripts/012_Battle/002_Move/005_Move_Effects_000-07F.rb
Data/Scripts/012_Battle/002_Move/006_Move_Effects_080-0FF.rb
Data/Scripts/012_Battle/002_Move/007_Move_Effects_100-17F.rb
Data/Scripts/012_Battle/003_Battle/001_PokeBattle_BattleCommon.rb
Data/Scripts/012_Battle/003_Battle/009_Battle_Action_Other.rb
Data/Scripts/012_Battle/004_AI/005_AI_Move_EffectScores.rb
Data/Scripts/012_Battle/005_Battle scene/004_PokeBattle_SceneElements.rb
Data/Scripts/012_Battle/007_BattleHandlers_Abilities.rb
Data/Scripts/012_Battle/008_BattleHandlers_Items.rb
Data/Scripts/015_Items/002_PItem_ItemEffects.rb
Data/Scripts/016_Pokemon/004_Pokemon_ShadowPokemon.rb
Data/Scripts/016_Pokemon/008_Pokemon_Storage.rb
Data/Scripts/017_UI/017_PScreen_PokemonStorage.rb
Data/Scripts/019_Other battles/004_PBattle_OrgBattleRules.rb

`isConst?(pkmn.species,PBSpecies,species)` and `isConst?(battler.species,PBSpecies,species)` are used extensively in Essentials's code. v18 added the `PokeBattle_Pokemon#isSpecies?` method, and I would like to propose using it instead of `isConst?`.
I've added `PokeBattle_Battler#isSpecies?`, which uses the new `isSpecies?` method:
```ruby
def isSpecies?(species)
return @pokemon && @pokemon.isSpecies?(species)
end
```
I've replaced every isConst? species check with the new methods. It should make the code easier to work with.

Check for Pokémon species with #isSpecies? instead of Object.isConst?

---

Data/Scripts/012_Battle/003_Battle/004_Battle_ExpAndMoveLearning.rb
Data/Scripts/013_Overworld/013_PField_DayCare.rb
Data/Scripts/015_Items/001_PItem_Items.rb
Data/Scripts/016_Pokemon/001_PokeBattle_Pokemon.rb
Data/Scripts/016_Pokemon/002_Pokemon_Forms.rb
Data/Scripts/016_Pokemon/003_Pokemon_MegaEvolution.rb
Data/Scripts/016_Pokemon/005_Pokemon_Evolution.rb
Data/Scripts/017_UI/022_PScreen_Trading.rb
Data/Scripts/019_Other battles/004_PBattle_OrgBattleRules.rb

I cleaned up `PokeBattle_Pokemon#hasItem?` a little (its functionality stays the same). I've also replaced all instances of `isConst?(pkmn.item,PBItems,item)` with `pkmn.hasItem?(item)`.

Refactor PokeBattle_Pokemon#hasItem? and use it instead of Object.isConst?

---

Data/Scripts/016_Pokemon/001_PokeBattle_Pokemon.rb

- Fixed name resetting on Pokémon with new species assigned that wasn't working as intended
- Improved naming on a variable

Fix nickname reset in Pokebattle_pokemon

---

Data/Scripts/009_Objects and windows/005_SpriteWindow_sprites.rb

Fixed assigning 10 as default value for delay in PngAnimatedBitmap
This fixes issue #18

Fixed default value for delay in PngAnimatedBitmap

---

Data/Scripts/016_Pokemon/001_PokeBattle_Pokemon.rb

I've done a number of changes in `016_Pokemon/PokeBattle_Pokemon.rb`:
- YARD-style documentation for every method and constant, seen [here](https://savordez.xyz/doctest/)
- Grouped methods related to status effects (`#status`, `#able?`, etc.) in a new "Status" section
- `#mail=` and `#statusCount=`  are no longer defined with `attr_writer`. They now validate their arguments.
- A couple of variables have been renamed to be more legible (`s` to `species`, `nat` to `current_nature`, etc.)
I believe there are too many methods defined with the `attr` methods in this class – I could give some of them the `#mail=` treatment.
I've made this a draft PR because the documentation isn't perfect yet. I feel like `#natureOverride` is a little confusing in particular, and the contest attribute writers …

Refactoring and YARD-style documentation of PokeBattle_Pokemon

---

Data/Scripts/001_Technical/006_DebugConsole.rb

Looks like an AllocConsole call was removed from ``Console.setup_console`` at some point. This PR restores it.

Fix debug console not opening

---

Data/Scripts/001_Technical/010_Validation.rb

This PR implements the `validate` method in `Kernel`, allowing for easy validation of classes and methods:
```ruby
validate foo => Integer, bar => :to_s # raises an error if foo is not an Integer or if bar doesn't implement #to_s
validate baz => [Sprite, Bitmap, Viewport] # raises an error if baz isn't a Sprite, Bitmap or Viewport
```
```ruby
class PokeBattle_Trainer
def money=(value)
validate value => Integer
@money = [[value, MAX_MONEY].min, 0].max
end
end
```
The method is private, meaning that code like `5.validate` will result in an error.
The implementation is largely inspired by @Marin-MK's own [validate.rb](https://github.com/Marin-MK/MK-Starter-Kit/blob/master/scripts/core/utils/validate.rb#L13).

Kernel.validate

---

Data/Scripts/009_Objects and windows/011_Messages.rb

This fixes issue #39 
Fixes the issue changing windowskin assignment, removing it from the command loop, to before color assignment

Edit order of commands in pbMessageDisplay to fix light text assignment

---

Data/Scripts/016_Pokemon/002_Pokemon_Forms.rb
Data/Scripts/016_Pokemon/005_Pokemon_Evolution.rb
PBS/pokemon.txt
PBS/pokemonforms.txt

Implementing Milcery's evolution.
Sweets are treated like evolution stones, except that using one of the sweets changes the form of Milcery right before evolving (hence a new "method" for evolving: ItemMilcery). As "dances" are not implemented, I replaced the nine "dances" with a simple computation of the level of Milcery (level modulo 9 is equivalent to one of the "dances").

Gen8 milcery

---

Data/Scripts/012_Battle/005_Battle scene/004_PokeBattle_SceneElements.rb

Small typo in the Essentials vanilla code that makes the EXP Full sound not play when the EXP bar fills up

Fix: EXP Full ding using wrong sound file

---

Data/Scripts/016_Pokemon/005_Pokemon_Evolution.rb

This fixes a bug in the baby species determination when both parents are holding an item, creating an egg that's fully evolved
Also fixes a related bug, in which it doesn't check items when doing a recursive baby species check, effectively ignoring incense if it has to recurse before reaching the insense'd mon.
Easy test situation is with Roserade, as it can be used for both situations.
On a related note, this was also a bug in v17.2, and it was a similar fix as here.
https://pastebin.com/pJJjqs5r

Fix for baby species to return the right species when checked with items

---

Data/Scripts/009_Objects and windows/001_BitmapCache.rb

Thread.critical is deprecated in Ruby 1.8.7: it does nothing. Also, it does not exist in Ruby 2+, so it will cause a crash in the future. The code in BitmapCache doesn't use Threads anyway, so Thread.critical can be safely removed.

Remove all Thread.critical usage from BitmapCache

---

Data/Scripts/009_Objects and windows/003_Window.rb
Data/Scripts/009_Objects and windows/004_SpriteWindow.rb

This PR removes `SpriteWindowCursorRect`, which was a duplicate of `WindowCursorRect`. `WindowCursorRect` has been reworked to use `super` and will no longer cause problems in newer Ruby versions.

Remove SpriteWindowCursorRect & fix WindowCursorRect

---

Data/Scripts/014_Trainers/001b_Trainer_deprecated.rb

This PR fixes a crash in `PokeBattle_Trainer.copy`. It also validates the given trainer object.

Fix a crash in PokeBattle_Trainer.copy

---

Data/Scripts/021_Debug/002_Animation editor/004_AnimEditor_ExportImport.rb
Data/Scripts/021_Debug/002_Animation editor/005_AnimEditor_Functions.rb
Data/Scripts/021_Debug/007_Editor_DataTypes.rb
Data/Scripts/021_Debug/008_Editor_Listers.rb
Data/Scripts/021_Debug/009_Editor_Utilities.rb

There is code in Essentials that calls a missing `doubleclick?` method. The statements are rescued, but raising and rescuing exceptions every frame isn't ideal. Also, since running the game with the debug console prints out an alert for every exception, including rescued ones, this happens:
This PR removes the code in question.

Remove all usage of missing doubleclick? method

---

Data/Scripts/001_Technical/002_Ruby Utilities.rb
Data/Scripts/012_Battle/005_Battle scene/004_PokeBattle_SceneElements.rb

This PR removes the following methods from `Ruby_Utilities.rb`:
- `Comparable#clamp` (already exists)
- `Boolean#to_i` (removed the Boolean class as it is unused)
- `String#starts_with?` (already exists as `String#start_with?`)
- `String#ends_with?` (already exists as `String#end_with?`)
- `String#bytesize` (already exists)
- `String#capitalize(!)` (already exists)
- `Integer#digits` (already exists)
- `Array#first` and `Array#last` (already exist)
- `Array#shuffle(!)` (already exists)
Ruby's own `Integer#digits` returns an array with the least significant digit as the first array element. That means that the method's only usage has to be appended with a call to `Array#reverse`, which I've done in this PR.

Remove unnecessary utilities

---

Data/Scripts/001_Technical/007_Errors.rb
Data/Scripts/020_System and utilities/005_PSystem_Utilities.rb
Data/Scripts/021_Debug/002_Animation editor/001_AnimEditor_SceneElements.rb
Data/Scripts/021_Debug/002_Animation editor/002_AnimEditor_ControlsButtons.rb
Data/Scripts/021_Debug/002_Animation editor/003_AnimEditor_Interpolation.rb

A small update to mkxp-z that gives support for delta timing, as well as making `Input.repeat?` and `Input.repeatex?` timing FPS-independent. The latter works by adjusting the frame counts required for a button to count as repeating whenever the FPS is changed (It's still the exact same as before if the framerate is set to the default), so it might break things that depend on specific values in `Input.count` and `Input.repeatcount`.
Using the delta clocks is easy, and all values returned by these functions are in microseconds:
+ `System.delta` tracks the amount of time passed since MKXP's startup
+ `Graphics.delta` tracks the amount of time passed since the last time `Graphics.update` was called
+ `Input.delta` tracks the amount of time passed since the last time `Input.update` was called …

Add support for timing using delta clocks

---

Data/Scripts/001_Technical/009_Deprecation.rb
Data/Scripts/014_Trainers/001b_Trainer_deprecated.rb
Data/Scripts/016_Pokemon/010_Pokemon_Deprecated.rb

This PR takes the unused `Module#deprecated_instance_method_alias` and `Module#deprecated_class_method_alias` and combines them into a single `Module#deprecated_method_alias` method. Its usage is as follows:
```ruby
class Foo
deprecated_method_alias :oldMethod, :new_method, removal_in: 'vXX'
deprecated_method_alias :oldMethod, :new_method, removal_in: 'vXX', class_method: true
end
```
Deprecated aliases call `Deprecation.warn_method` automatically.
This PR takes the existing deprecated aliases and replaces them with calls to `deprecated_method_alias`.

Module#deprecated_method_alias

---

Data/Scripts/012_Battle/007_BattleHandlers_Abilities.rb

the accuracy should be 50(percent) instead of 0 (which would make moves Sure Hit)

Wonder Skin

---

Data/Scripts/016_UI/014_UI_Save.rb

pbSave's deprecation message urged people to "Use v20 instead". This PR fixes that.

Fix pbSave's incorrect deprecation message

---

Data/Scripts/011_Battle/003_BattleHandlers_Abilities.rb

Variable `oldAbil` in the Mummy ability was being treated like an integer. It's a symbol. 
Fixes #114

MUMMY Ability bug fix

---

Data/Scripts/012_Overworld/002_Battle triggering/003_Overworld_WildEncounters.rb

Discovered favored types were still set to pull the value which is now relative probability rather than species type, fixed this error

Fix Crash on attempting to get Favored Types

---

Data/Scripts/001_Technical/001_MKXP_Compatibility.rb

The `draw_text` override will cause the game to crash if it is used with a Rect. This PR fixes the issue.

Fix Bitmap#draw_text override not accepting Rect argument

---

Data/Scripts/001_Settings.rb
Data/Scripts/007_Objects and windows/011_Messages.rb
Data/Scripts/011_Battle/002_Battler/005_Battler_StatStages.rb
Data/Scripts/011_Battle/002_Battler/007_Battler_UseMove.rb
Data/Scripts/011_Battle/006_Other battle code/007_BattleAnimationPlayer.rb
Data/Scripts/012_Overworld/002_Battle triggering/001_Overworld_BattleStarting.rb
Data/Scripts/016_UI/015_UI_Options.rb

- Removed pbRefreshSceneMap which was only used in the Options screen
- Fixed Ability Splash setting completely negating stat blocking attempts
- Fixed Beak blast always failing because its effect would always reset at the start of the Pokemon's turn
- Fixed crash when playing an animation in the Animation Editor
- Added default terrain effects based on weather, like in Gen 8.

More bugfixes (and one Gen 8 addition)

---

.gitignore

This PR adds .mkproj files to the .gitignore file. It should clean up the unstaged change list for those who test and/or use RPG Studio MK by Marin.

Add .mkproj files to .gitignore

---

Data/Scripts/011_Battle/003_Move/005_MoveEffects_Misc.rb

Use the `.max` function in Substitute's code instead of an inline if for checking if the HP of the substitute would be less than 1. The `.max` function (used for arrays) searches the greatest value in the array, so `[15,1].max` will output `15`.
I am sure that will work.

Use the .max function in Substitute's code

---

Data/Scripts/011_Battle/003_Move/011_MoveEffects_Items.rb
Data/Scripts/011_Battle/003_Move/012_MoveEffects_ChangeMoveEffect.rb

This flag had 3 N's in its name where it was supposed to be two. In the move PBS files, the flag is spelled correctly.

Fixed typo in "CannotMetronome"

---

Data/Scripts/001_Technical/005_PluginManager.rb

This PR edits the echoed line `Loaded Plugin: *plugin name*` to  display the version number of the plugin along with the name. This would be very useful for plugin makers to debug issues with their plugins, because some users don't update their plugins on time and not every plugin is displayed in `Essentials::ERROR_TEXT`.

Display version number of plugins in the console

---

Data/Scripts/007_Objects and windows/011_Messages.rb

`/[Cc]/` takes up 2 more chars than `/c/i`, so changed to the latter syntax.

Minor regex fix

---

Data/Scripts/018_Alternate battle modes/002_Battle Frontier rules/002_Challenge_Rulesets.rb

Challenge min pokémon, combined with team/pokémon rules aren't working properly.
You can reproduce adding the below code, having the demo party and calling setRule.
```
def pbSomeRules
ret = PokemonChallengeRules.new 
ret.addTeamRule(SpeciesClause.new)
ret.addPokemonRule(HeightRestriction.new(1))
ret.ruleset.setNumberRange(1,6)
return ret
end
def setRule 
pbBattleChallenge.set("someChallenge",7,pbSomeRules)
pbBattleChallenge.start
print pbHasEligible?
end
```
In this scenario you have 2 pokémon eligible, but the script returns false, since it requires the max (6) to be eligible.

Fix challenge min length

---

Data/Scripts/001_Technical/002_RubyUtilities.rb

- `^` may match the position right after a newline character, and `$` may match right before the newline character (due to the multiline flag being enabled by default), so substing these with `\A` and `\Z`.
- Substed both instances of `[0-9]` with the shorthand `\d`.
- Removed capturing group around the first `\d+`.

Edited string methods

---

Data/Scripts/011_Battle/003_Move/007_MoveEffects_BattlerOther.rb

This is already handled by the `Powder` flag on Magic Powder, so this is unneeded.

Remove powder check from Magic Powder

---

Data/Scripts/016_UI/005_UI_Party.rb

On a selection like Battle Tower's, if player places the cursor into cancel and press up, the cursor doesn't move/loop after the commit dcba641 . This Pull Request fix this.

Fixed party navigation on pokémon selection
